[Fix] Qrc xml parser in QQ Music API GetVerbatimLyric
jitwxs/163MusicLyrics pull request #203
Opened 2024-02-26 12:17 UTC by WXRIW

移除字符串头部的 BOM 标识 (如果有)，以解决部分歌词无法被解析的问题。

因为我在我的一个项目里使用了本项目的代码，故顺带提交 PR 进行修复。
https://github.com/WXRIW/Lyricify-Lyrics-Helper/commit/87ad7d7035343921084b4f7ef2fe75a57a3f4074

2024-05-16 12:26 UTC, textGamex approved these changes

2024-05-18 07:47 UTC, textGamex requested changes

2024-05-18 07:47 UTC, textGamex commented on MusicLyricApp/Api/Music/QQMusicNativeApi.cs
> +                    string _byteOrderMarkUtf8 = Encoding.UTF8.GetString(Encoding.UTF8.GetPreamble());
局部变量名请遵守C#约定, 使用小驼峰式大小写.

2024-06-21 14:53 UTC, jitwxs approved these changes

2024-06-21 14:53 UTC, merged